name: AWS Sustainability Scan

on:
  push:
    branches: [ main ]

jobs:
  sustainability-scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: AWS Sustainability Scanner
        uses: aws-actions/sustainability-scanner@v1
        with:
          directory: "templates"
